name: $name
version: $version
main: $group.${name}Plugin
api-version: "$apiVersion"
folia-supported: true
authors: [ Hydrolien ]
description: $description
website: https://github.com/Mvndi/$name
dependencies:
  server:
    Worlds:
      required: true
      load: BEFORE
    Chunky:
      required: false
      load: BEFORE
    Towny:
      required: false
      load: BEFORE
    TownyRoads:
      required: false
      load: BEFORE